/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kaelthas_demo_ndk_test_AddNum */

#ifndef _Included_com_kaelthas_demo_ndk_test_AddNum
#define _Included_com_kaelthas_demo_ndk_test_AddNum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kaelthas_demo_ndk_test_AddNum
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kaelthas_demo_ndk_test_AddNum_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
